FROM ruby:3.3.3-slim

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev git && rm -rf /var/lib/apt/lists/*

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
